version: "3.7"

services:
  caddy:
    container_name: humanbios-tg
    image: humanbios-tg
    restart: unless-stopped
    ports:
    - 8888:8888

networks:
  default:
    external:
      name: caddynet
